### ISSUE TITLE
Am I the asshole voting

### ISSUE THREAD

**Issue by rohbit** [shadedblue/CampingBot#7]
Similar to /rant except /aita

Possible responses.

Yes
Kinda
No

Each response has a number associated with it.

Asshole would be a score above some value. Perhaps average the total like in ranked.

At the end could randomize responses after vote, i.e. after being deemed an asshole, it would say, "You are the gapiest bunghole".

**Comment by shadedblue** [comment]
should this use the reddit style voting of:
YTA
ESH
NTA
?

**Comment by shadedblue** [comment]
Also, +1 to bunghole insulting at the end

**Comment by rohbit** [comment]
Love the "YTA" and NTA, not sure what ESH means.
